version: "2"
services:
  match:
    image: spielerua/changed:latest
    ports:
      - 127.0.0.1:8888:8888
    command:
      [
        "/wait-for-it.sh",
        "-t",
        "60",
        "elasticsearch:9200",
        "--",
        "gunicorn",
        "-b",
        "0.0.0.0:8888",
        "-w",
        "4",
        "server:app",
      ]
    links:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:6.8.19
    ports:
      - 127.0.0.1:9200:9200
