version: "2.2"
services:
  match:
    restart: always
    image: spielerua/changed:latest
    ports:
      - 127.0.0.1:8888:8888
    command:
      [
        "/wait-for-it.sh",
        "-t",
        "60",
        "elasticsearch:9200",
        "--",
        "gunicorn",
        "-b",
        "0.0.0.0:8888",
        "-w",
        "4",
        "server:app",
      ]
    links:
      - elasticsearch
  elasticsearch:
    restart: always
    cpu_percent: 50
    mem_limit: 3500m
    mem_reservation: 512M
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.19
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

volumes:
  esdata1:
    driver: local
