apiVersion: extensions/v1beta1v1
kind: Deployment
metadata:
  name: match-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match
          image: spielerua/changed:latest
          ports:
            - containerPort: 80
          env:
            - name: WORKER_COUNT
              value: "4"
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: match
                  key: elasticsearch.url
            - name: ELASTICSEARCH_INDEX
              valueFrom:
                secretKeyRef:
                  name: match
                  key: elasticsearch.index
            - name: ELASTICSEARCH_DOC_TYPE
              valueFrom:
                secretKeyRef:
                  name: match
                  key: elasticsearch.doc-type
